# Добавено в лабораторно упражнение 9
networks:
  jedi:

services:
  # Добавено в лабораторно упражнение 7
  app:
    container_name: padawan-6156-app
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
#    depends_on:
#      - db
    networks: # Добавено в лабораторно упражнение 9
      - jedi
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tasksdb
      SPRING_DATASOURCE_USERNAME: padawan
      SPRING_DATASOURCE_PASSWORD: R2D2c3p0
  # Добавено в лабораторно упражнение 9
  db:
    container_name: padawan-6156-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: R2D2c3p0
      POSTGRES_USER: padawan
      POSTGRES_DB: tasksdb
    networks:
      - jedi