# ????????? ? ??????????? ?????????? 7
spring.application.name=task_manager
server.port=9000
server.servlet.context-path=/api
# ???????? ? ??????????? ?????????? 9
spring.datasource.url=jdbc:h2:file:./data/tasksdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=padawan
spring.datasource.password=R2D2c3p0

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=create

